spring:
  messages:
    basename: messages
  datasource:
    url: jdbc:h2:tcp://localhost/~/project-backend
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

